# Generated by Django 5.2.8 on 2026-01-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_project_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='experience',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
